title: Jaime Pastor 
logo: "/images/headshot.png?raw=true" 
description: >
  <br>
  Data scientist
  <br><br>
  <a href="https://www.linkedin.com/in/jaimepastor2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 
